name: mf_dbt_proj
profile: mf_dbt_proj
version: 1.0.0
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  mf_dbt_proj:
    0_staging:
      +schema: sh_analytics
    1_dataware:
      +schema: sh_analytics
      +materialized: table
    1_datamart:
      +schema: sh_reports
      +materialized: table
flags:
  require_generic_test_arguments_property: true